/**
 * src/schema.ts — **自动生成，请勿手改**（由 scripts/gen-schema.mjs 生成）。
 *
 * 来源：/home/h/app/VCPToolBox/sandbox/classroom-flow/full/knowledge_base.sqlite
 * 共 53 条 DDL（table/index/trigger）。
 * 依据 DESIGN.md §9：表为 VCP schema 子集，DDL 逐字取自 VCPToolBox。
 */

/** 按序执行的建表语句（全部 IF NOT EXISTS 语义由参考 DDL 自身保证；本函数幂等）。 */
export const SCHEMA_STATEMENTS: readonly string[] = [
  "CREATE TABLE chunks (\n        id INTEGER PRIMARY KEY AUTOINCREMENT,\n        file_id INTEGER NOT NULL,\n        chunk_index INTEGER NOT NULL,\n        content TEXT NOT NULL,\n        vector BLOB,\n        FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE\n    );",
  "CREATE TABLE file_tags (\n        file_id INTEGER NOT NULL,\n        tag_id INTEGER NOT NULL,\n        position INTEGER NOT NULL DEFAULT 0,\n        PRIMARY KEY (file_id, tag_id),\n        FOREIGN KEY(file_id) REFERENCES files(id) ON DELETE CASCADE,\n        FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE\n    );",
  "CREATE TABLE files (\n        id INTEGER PRIMARY KEY AUTOINCREMENT,\n        path TEXT UNIQUE NOT NULL,\n        diary_name TEXT NOT NULL,\n        checksum TEXT NOT NULL,\n        mtime INTEGER NOT NULL,\n        size INTEGER NOT NULL,\n        updated_at INTEGER\n    );",
  "CREATE TABLE kv_store (\n        key TEXT PRIMARY KEY,\n        value TEXT,\n        vector BLOB\n    );",
  "CREATE TABLE migration_deleted_chunks (\n        cache_file_id INTEGER NOT NULL,\n        chunk_index INTEGER NOT NULL,\n        vector BLOB NOT NULL,\n        PRIMARY KEY (cache_file_id, chunk_index),\n        FOREIGN KEY(cache_file_id) REFERENCES migration_deleted_files(id) ON DELETE CASCADE\n    );",
  "CREATE TABLE migration_deleted_files (\n        id INTEGER PRIMARY KEY AUTOINCREMENT,\n        old_path TEXT NOT NULL,\n        old_diary_name TEXT NOT NULL,\n        checksum TEXT NOT NULL,\n        size INTEGER NOT NULL,\n        chunk_count INTEGER NOT NULL,\n        deleted_at INTEGER NOT NULL,\n        expires_at INTEGER NOT NULL\n    );",
  "CREATE TABLE rivermemo_artifacts (\n        artifact_sig TEXT PRIMARY KEY,\n        schema_version TEXT NOT NULL,\n        algorithm_version TEXT NOT NULL,\n        source_v9_artifact_sig TEXT NOT NULL,\n        source_graph_generation TEXT NOT NULL,\n        model_sig TEXT NOT NULL,\n        config_hash TEXT NOT NULL,\n        database_generation TEXT NOT NULL,\n        provenance_generation TEXT NOT NULL,\n        payload_codec TEXT NOT NULL DEFAULT 'gzip-json-v1',\n        payload_checksum TEXT,\n        payload BLOB,\n        status TEXT NOT NULL,\n        error_message TEXT,\n        node_count INTEGER NOT NULL DEFAULT 0,\n        edge_count INTEGER NOT NULL DEFAULT 0,\n        created_at INTEGER NOT NULL,\n        updated_at INTEGER NOT NULL,\n        published_at INTEGER\n    );",
  "CREATE TABLE tag_index_baseline_entries (\n        generation INTEGER NOT NULL,\n        tag_id INTEGER NOT NULL,\n        vector_version INTEGER NOT NULL,\n        PRIMARY KEY (generation, tag_id),\n        FOREIGN KEY(generation) REFERENCES tag_index_baselines(generation) ON DELETE CASCADE\n    );",
  "CREATE TABLE tag_index_baselines (\n        generation INTEGER PRIMARY KEY,\n        slot TEXT NOT NULL CHECK(slot IN ('a', 'b')),\n        dimension INTEGER NOT NULL,\n        model_sig TEXT NOT NULL,\n        tag_count INTEGER NOT NULL,\n        status TEXT NOT NULL CHECK(status IN ('building', 'ready')),\n        created_at INTEGER NOT NULL\n    );",
  "CREATE TABLE tag_intrinsic_residual_status (\n        tag_id INTEGER NOT NULL,\n        artifact_sig TEXT NOT NULL,\n        status TEXT NOT NULL,\n        neighbor_count INTEGER NOT NULL DEFAULT 0,\n        error_message TEXT,\n        computed_at INTEGER NOT NULL,\n        PRIMARY KEY (tag_id, artifact_sig),\n        FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE\n    );",
  "CREATE TABLE tag_intrinsic_residuals (\n        tag_id INTEGER PRIMARY KEY,\n        residual_energy REAL NOT NULL,\n        neighbor_count INTEGER NOT NULL,\n        computed_at TEXT NOT NULL DEFAULT (datetime('now'))\n    , raw_residual_ratio REAL, v8_3_compat_gain REAL, v9_anchor_gain REAL, model_sig TEXT, artifact_sig TEXT, algorithm_version TEXT, config_hash TEXT, status TEXT NOT NULL DEFAULT 'computed');",
  "CREATE TABLE tag_pair_similarity (\n        tag_a INTEGER NOT NULL,\n        tag_b INTEGER NOT NULL,\n        similarity REAL NOT NULL,\n        model_sig TEXT NOT NULL,\n        computed_at INTEGER NOT NULL,\n        PRIMARY KEY (tag_a, tag_b),\n        FOREIGN KEY (tag_a) REFERENCES tags(id) ON DELETE CASCADE,\n        FOREIGN KEY (tag_b) REFERENCES tags(id) ON DELETE CASCADE\n    );",
  "CREATE TABLE tag_pair_similarity_status (\n        tag_a INTEGER NOT NULL,\n        tag_b INTEGER NOT NULL,\n        model_sig TEXT NOT NULL,\n        artifact_sig TEXT NOT NULL,\n        status TEXT NOT NULL,\n        similarity REAL,\n        min_similarity REAL NOT NULL,\n        computed_at INTEGER NOT NULL,\n        PRIMARY KEY (tag_a, tag_b, artifact_sig),\n        FOREIGN KEY (tag_a) REFERENCES tags(id) ON DELETE CASCADE,\n        FOREIGN KEY (tag_b) REFERENCES tags(id) ON DELETE CASCADE\n    );",
  "CREATE TABLE tagmemo_artifacts (\n        artifact_sig TEXT PRIMARY KEY,\n        asset_type TEXT NOT NULL,\n        model_sig TEXT NOT NULL,\n        graph_generation TEXT NOT NULL,\n        algorithm_version TEXT NOT NULL,\n        config_hash TEXT NOT NULL,\n        effective_config TEXT NOT NULL,\n        status TEXT NOT NULL DEFAULT 'ready',\n        created_at INTEGER NOT NULL,\n        updated_at INTEGER NOT NULL\n    );",
  "CREATE TABLE tags (\n        id INTEGER PRIMARY KEY AUTOINCREMENT,\n        name TEXT UNIQUE NOT NULL,\n        vector BLOB,\n        vector_version INTEGER NOT NULL DEFAULT 1\n    );",
  "CREATE TABLE v10_chunk_tag_geometry (\n        chunk_id INTEGER NOT NULL,\n        tag_id INTEGER NOT NULL,\n        model_sig TEXT NOT NULL,\n        dimension INTEGER NOT NULL,\n        chunk_vector_sig TEXT NOT NULL,\n        tag_vector_sig TEXT NOT NULL,\n        cosine REAL NOT NULL,\n        updated_at INTEGER NOT NULL,\n        PRIMARY KEY (chunk_id, tag_id, model_sig, dimension),\n        FOREIGN KEY(chunk_id) REFERENCES chunks(id) ON DELETE CASCADE,\n        FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE\n    );",
  "CREATE TABLE v10_derived_asset_status (\n        asset_type TEXT NOT NULL,\n        model_sig TEXT NOT NULL,\n        dimension INTEGER NOT NULL,\n        source_generation TEXT NOT NULL,\n        row_count INTEGER NOT NULL DEFAULT 0,\n        status TEXT NOT NULL,\n        error_message TEXT,\n        updated_at INTEGER NOT NULL,\n        PRIMARY KEY (asset_type, model_sig, dimension)\n    );",
  "CREATE TABLE v10_vector_metrics (\n        entity_type TEXT NOT NULL CHECK(entity_type IN ('tag', 'chunk')),\n        entity_id INTEGER NOT NULL,\n        model_sig TEXT NOT NULL,\n        dimension INTEGER NOT NULL,\n        vector_sig TEXT NOT NULL,\n        l2_norm REAL NOT NULL,\n        updated_at INTEGER NOT NULL,\n        PRIMARY KEY (entity_type, entity_id, model_sig, dimension)\n    );",
  "CREATE INDEX idx_chunks_file ON chunks(file_id);",
  "CREATE INDEX idx_file_tags_composite ON file_tags(tag_id, file_id);",
  "CREATE INDEX idx_file_tags_tag ON file_tags(tag_id);",
  "CREATE INDEX idx_files_diary ON files(diary_name);",
  "CREATE INDEX idx_intrinsic_residual_artifact\n        ON tag_intrinsic_residuals(artifact_sig);",
  "CREATE INDEX idx_intrinsic_residual_model\n        ON tag_intrinsic_residuals(model_sig);",
  "CREATE INDEX idx_intrinsic_residual_status_artifact\n        ON tag_intrinsic_residual_status(artifact_sig, status);",
  "CREATE INDEX idx_migration_deleted_expiry\n        ON migration_deleted_files(expires_at);",
  "CREATE INDEX idx_migration_deleted_lookup\n        ON migration_deleted_files(checksum, size, expires_at);",
  "CREATE INDEX idx_pair_sim_model\n        ON tag_pair_similarity(model_sig);",
  "CREATE INDEX idx_pair_sim_status_artifact\n        ON tag_pair_similarity_status(artifact_sig, status);",
  "CREATE INDEX idx_pair_sim_status_model\n        ON tag_pair_similarity_status(model_sig);",
  "CREATE INDEX idx_pair_sim_status_tag_b\n        ON tag_pair_similarity_status(tag_b);",
  "CREATE INDEX idx_pair_sim_tag_b\n        ON tag_pair_similarity(tag_b);",
  "CREATE INDEX idx_rivermemo_artifacts_compatible\n        ON rivermemo_artifacts(\n            source_v9_artifact_sig,\n            model_sig,\n            config_hash,\n            database_generation,\n            status,\n            updated_at\n        );",
  "CREATE INDEX idx_rivermemo_artifacts_status\n        ON rivermemo_artifacts(status, updated_at);",
  "CREATE INDEX idx_tag_index_baseline_entries_generation\n        ON tag_index_baseline_entries(generation);",
  "CREATE INDEX idx_tagmemo_artifacts_lookup\n        ON tagmemo_artifacts(asset_type, model_sig, status);",
  "CREATE INDEX idx_v10_chunk_tag_geometry_tag\n        ON v10_chunk_tag_geometry(tag_id, model_sig, dimension);",
  "CREATE INDEX idx_v10_vector_metrics_generation\n        ON v10_vector_metrics(model_sig, dimension, entity_type);",
  "CREATE TRIGGER trg_pairwise_file_tags_delete_generation\n    AFTER DELETE ON file_tags\n    BEGIN\n        UPDATE kv_store\n        SET value = CAST(COALESCE(CAST(value AS INTEGER), 0) + 1 AS TEXT)\n        WHERE key = 'tagmemo_pairwise_fact_generation';\n    END;",
  "CREATE TRIGGER trg_pairwise_file_tags_insert_generation\n    AFTER INSERT ON file_tags\n    BEGIN\n        UPDATE kv_store\n        SET value = CAST(COALESCE(CAST(value AS INTEGER), 0) + 1 AS TEXT)\n        WHERE key = 'tagmemo_pairwise_fact_generation';\n    END;",
  "CREATE TRIGGER trg_pairwise_file_tags_update_generation\n    AFTER UPDATE OF file_id, tag_id ON file_tags\n    WHEN OLD.file_id IS NOT NEW.file_id OR OLD.tag_id IS NOT NEW.tag_id\n    BEGIN\n        UPDATE kv_store\n        SET value = CAST(COALESCE(CAST(value AS INTEGER), 0) + 1 AS TEXT)\n        WHERE key = 'tagmemo_pairwise_fact_generation';\n    END;",
  "CREATE TRIGGER trg_pairwise_tags_delete_generation\n    AFTER DELETE ON tags\n    BEGIN\n        UPDATE kv_store\n        SET value = CAST(COALESCE(CAST(value AS INTEGER), 0) + 1 AS TEXT)\n        WHERE key = 'tagmemo_pairwise_fact_generation';\n    END;",
  "CREATE TRIGGER trg_pairwise_tags_insert_generation\n    AFTER INSERT ON tags\n    BEGIN\n        UPDATE kv_store\n        SET value = CAST(COALESCE(CAST(value AS INTEGER), 0) + 1 AS TEXT)\n        WHERE key = 'tagmemo_pairwise_fact_generation';\n    END;",
  "CREATE TRIGGER trg_pairwise_tags_vector_generation\n    AFTER UPDATE OF vector ON tags\n    WHEN OLD.vector IS NOT NEW.vector\n    BEGIN\n        UPDATE kv_store\n        SET value = CAST(COALESCE(CAST(value AS INTEGER), 0) + 1 AS TEXT)\n        WHERE key = 'tagmemo_pairwise_fact_generation';\n    END;",
  "CREATE TRIGGER trg_tags_vector_version\n    AFTER UPDATE OF vector ON tags\n    WHEN OLD.vector IS NOT NEW.vector\n    BEGIN\n        UPDATE tags\n        SET vector_version = OLD.vector_version + 1\n        WHERE id = NEW.id;\n    END;",
  "CREATE TRIGGER trg_v10_chunks_delete_stale\n    AFTER DELETE ON chunks BEGIN\n        UPDATE v10_derived_asset_status\n        SET status = 'stale', error_message = 'chunks-deleted',\n            updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000;\n    END;",
  "CREATE TRIGGER trg_v10_chunks_insert_stale\n    AFTER INSERT ON chunks BEGIN\n        UPDATE v10_derived_asset_status\n        SET status = 'stale', error_message = 'chunks-inserted',\n            updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000;\n    END;",
  "CREATE TRIGGER trg_v10_chunks_vector_stale\n    AFTER UPDATE OF vector ON chunks BEGIN\n        UPDATE v10_derived_asset_status\n        SET status = 'stale', error_message = 'chunk-vector-updated',\n            updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000;\n    END;",
  "CREATE TRIGGER trg_v10_file_tags_delete_stale\n    AFTER DELETE ON file_tags BEGIN\n        UPDATE v10_derived_asset_status\n        SET status = 'stale', error_message = 'file-tags-deleted',\n            updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000;\n    END;",
  "CREATE TRIGGER trg_v10_file_tags_insert_stale\n    AFTER INSERT ON file_tags BEGIN\n        UPDATE v10_derived_asset_status\n        SET status = 'stale', error_message = 'file-tags-inserted',\n            updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000;\n    END;",
  "CREATE TRIGGER trg_v10_tags_delete_stale\n    AFTER DELETE ON tags BEGIN\n        UPDATE v10_derived_asset_status\n        SET status = 'stale', error_message = 'tags-deleted',\n            updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000;\n    END;",
  "CREATE TRIGGER trg_v10_tags_insert_stale\n    AFTER INSERT ON tags BEGIN\n        UPDATE v10_derived_asset_status\n        SET status = 'stale', error_message = 'tags-inserted',\n            updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000;\n    END;",
  "CREATE TRIGGER trg_v10_tags_vector_stale\n    AFTER UPDATE OF vector ON tags BEGIN\n        UPDATE v10_derived_asset_status\n        SET status = 'stale', error_message = 'tag-vector-updated',\n            updated_at = CAST(strftime('%s','now') AS INTEGER) * 1000;\n    END;"
]
